name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push Backend
        run: |
          docker build -t youruser/backend:v1 ./backend
          docker push youruser/backend:v1
      - name: Build and Push Frontend
        run: |
          docker build -t youruser/frontend:v1 ./frontend
          docker push youruser/frontend:v1
